
import os

# === Environment variables ===
OPENAI_API_KEY = os.environ.get("OPENAI_API_KEY", "")
PINECONE_API_KEY = os.environ.get("PINECONE_API_KEY", "")
PINECONE_INDEX = os.environ.get("PINECONE_INDEX", "lsfusion")
PINECONE_NAMESPACE = os.environ.get("PINECONE_NAMESPACE", "")

# Embedding model
EMBEDDING_MODEL = os.environ.get("EMBEDDING_MODEL", "text-embedding-3-large")

# Metadata keys
TEXT = "text"
SOURCETYPE = "sourceType"

SOURCETYPE_DOCUMENTATION = "documentation"
SOURCETYPE_DOCUMENTATION_PARADIGM = "paradigm"
SOURCETYPE_DOCUMENTATION_HOWTO = "how-to"
SOURCETYPE_DOCUMENTATION_LANGUAGE = "language"
SOURCETYPE_DOCUMENTATION_TUTORIAL = "tutorial"
SOURCETYPE_ARTICLES = "articles"
SOURCETYPE_TALKS = "talks"

# Canonical combined source-type identifiers
SOURCETYPE_DOC_PARADIGM = f"{SOURCETYPE_DOCUMENTATION}-{SOURCETYPE_DOCUMENTATION_PARADIGM}"
SOURCETYPE_DOC_HOWTO = f"{SOURCETYPE_DOCUMENTATION}-{SOURCETYPE_DOCUMENTATION_HOWTO}"
SOURCETYPE_DOC_LANGUAGE = f"{SOURCETYPE_DOCUMENTATION}-{SOURCETYPE_DOCUMENTATION_LANGUAGE}"
SOURCETYPE_DOC_TUTORIAL = f"{SOURCETYPE_DOCUMENTATION}-{SOURCETYPE_DOCUMENTATION_TUTORIAL}"

# TopK per source type (mirrors your Java setup, but without 'system')
TOP_K = {
    SOURCETYPE_DOC_PARADIGM: 3,
    SOURCETYPE_DOC_HOWTO: 3,
    SOURCETYPE_DOC_LANGUAGE: 3,
    SOURCETYPE_DOC_TUTORIAL: 3,
    SOURCETYPE_ARTICLES: 3,
    SOURCETYPE_TALKS: 3,
}
