from __future__ import annotations
from dataclasses import dataclass, field, asdict
from typing import List, Optional
from antlr4 import InputStream, CommonTokenStream, Token
from antlr4.error.ErrorListener import ErrorListener

from typing import List, Optional
from pydantic import BaseModel, Field

# ---- generated by ANTLR (Python3 target) ----
from .LsfJSLogicsLexer import LsfJSLogicsLexer
from .LsfJSLogicsParser import LsfJSLogicsParser

START_RULE = "statements"  # fixed entry rule

# ---------------------------
# Data models (structured out)
# ---------------------------

class DSLError(BaseModel):
    """Single syntax or semantic issue found in DSL text."""
    type: str = Field(..., description="Error category: 'syntax' or 'semantic'.")
    message: str = Field(..., description="Readable explanation of the problem.")
    line: int = Field(..., description="Line number (1-based) where error starts.")
    column: int = Field(..., description="Column number (0-based) where error starts.")
    found: Optional[str] = Field(None, description="Actual token or fragment found, if any.")
    expected: List[str] = Field(default_factory=list, description="List of tokens or constructs expected at this point.")
    hint: Optional[str] = Field(None, description="Short fix suggestion to resolve the issue.")
    excerpt: Optional[str] = Field(None, description="Line of source where the error occurred.")
    pointer: Optional[str] = Field(None, description="Caret marker showing error position in the excerpt.")

class DSLValidationResult(BaseModel):
    """Structured validation result for DSL input."""
    ok: bool = Field(..., description="True if DSL text parsed successfully without errors.")
    errors: List[DSLError] = Field(default_factory=list, description="Detailed error entries (empty if ok=True).")

# ---------------------------
# Internal helpers
# ---------------------------

def _vocabulary(parser: LsfJSLogicsParser):
    return list(parser.literalNames or []), list(parser.symbolicNames or [])

def _token_name(tok_type: int, lit, sym):
    if tok_type == Token.EOF:
        return "EOF"
    if 0 <= tok_type < len(lit) and lit[tok_type]:
        return lit[tok_type]
    if 0 <= tok_type < len(sym) and sym[tok_type]:
        return sym[tok_type]
    return f"<TOK:{tok_type}>"

def _expected_tokens(parser: LsfJSLogicsParser) -> List[str]:
    lit, sym = _vocabulary(parser)
    try:
        types = parser.getExpectedTokens().toList()
    except Exception:
        return []
    names, seen = [], set()
    for t in types:
        n = _token_name(t, lit, sym)
        if n not in seen:
            seen.add(n); names.append(n)
    return names[:20]

def _line_excerpt(source: str, line: int, column: int, width: int = 1):
    lines = source.splitlines()
    if 1 <= line <= len(lines):
        ln = lines[line - 1]
        caret = " " * max(0, column) + "^" * max(1, width)
        return ln, caret
    return "", ""

class _CollectingErrorListener(ErrorListener):
    def __init__(self, source_text: str, parser: Optional[LsfJSLogicsParser] = None):
        super().__init__()
        self.source_text = source_text
        self.parser = parser
        self.errors: List[DSLError] = []

    def syntaxError(self, recognizer, offendingSymbol, line, column, msg, e):
        found_text = offendingSymbol.text if isinstance(offendingSymbol, Token) else None
        expected = _expected_tokens(self.parser) if self.parser else []

        hint = None
        low = (msg or "").lower()
        if found_text is None and expected:
            hint = f"Insert {expected[0]} here."
        elif "missing" in low and expected and found_text:
            hint = f"Insert {expected[0]} before '{found_text}'."
        elif "mismatched" in low and expected and found_text:
            hint = f"Replace '{found_text}' with {expected[0]}."
        elif offendingSymbol and offendingSymbol.type == Token.EOF and expected:
            hint = f"Add {expected[0]} before end of input."

        excerpt, pointer = _line_excerpt(self.source_text, line, column)
        self.errors.append(
            DSLError(
                type="syntax",
                message=msg,
                line=line,
                column=column,
                found=found_text,
                expected=expected,
                hint=hint,
                excerpt=excerpt,
                pointer=pointer,
            )
        )

# ---------------------------
# Public API
# ---------------------------

def validate_dsl_statements_tool(text: str) -> DSLValidationResult:
    """
    Validate full DSL input using the fixed start rule 'script'.
    Returns DSLValidationResult with syntax diagnostics suitable for MCP structured outputs.
    """
    input_stream = InputStream(text)
    lexer = LsfJSLogicsLexer(input_stream)
    tokens = CommonTokenStream(lexer)
    parser = LsfJSLogicsParser(tokens)

    # Collect lex + parse errors
    lexer.removeErrorListeners(); parser.removeErrorListeners()
    lex_listener = _CollectingErrorListener(text)
    parse_listener = _CollectingErrorListener(text, parser)
    lexer.addErrorListener(lex_listener); parser.addErrorListener(parse_listener)

    # Parse from the fixed entry rule
    try:
        getattr(parser, START_RULE)()
    except AttributeError:
        # If the generated parser doesn't have 'script', return an internal error
        return DSLValidationResult(
            ok=False,
            errors=[DSLError(
                type="internal",
                message=f"Start rule '{START_RULE}' not found in parser.",
                line=1, column=0,
                hint="Update START_RULE or regenerate parser to match grammar."
            )]
        )

    errors = lex_listener.errors + parse_listener.errors
    return DSLValidationResult(ok=(len(errors) == 0), errors=errors)
